This notebook looks at correct percent of elections winners predicted *for the test set*. 

In [1]:
from fastbook import *
setup_book()

import pandas as pd
import numpy as np
from pandas.api.types import is_string_dtype, is_numeric_dtype, is_categorical_dtype
from fastai.tabular.all import *
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from dtreeviz.trees import *
from IPython.display import Image, display_svg, SVG

In [2]:
def classif_accur(preds, y): 
    pred_margins = preds - 0.500
    pred_repub_wins = np.array([1 if x>0 else 0 for x in pred_margins])
    
    margins = np.array(y - 0.500)
    repub_wins = np.array([1 if x>0 else 0 for x in margins])
    correct = repub_wins==pred_repub_wins

    return sum(correct)/len(correct)

In [3]:
test_set = load_pickle('..\\prepared_data\\prepared_test_set_v1.pkl')

<font size = 6> Decision Tree </font>

In [4]:
best_tree = load_pickle('trained_models\\dtree_best.pkl')

In [5]:
classif_accur(best_tree.predict(test_set.train.xs), test_set.train.y)

0.6989247311827957

<font size = 6> Random Forest </font>

In [6]:
best_rf = load_pickle('trained_models\\rf_best.pkl')

In [7]:
classif_accur(best_rf.predict(test_set.train.xs), test_set.train.y)

0.8817204301075269

<font size =6 > Neural Net</font>

In [8]:
dl = load_pickle('..\\prepared_data\\dataloader_for_inference_neural_net.pkl')

In [9]:
best_net = load_pickle('trained_models\\0.076_error_neural_net.pkl')

In [10]:
preds = best_net.get_preds(dl=dl)
preds

(tensor([[0.6514],
         [0.7046],
         [0.5391],
         [0.6174],
         [0.4523],
         [0.3538],
         [0.4022],
         [0.3037],
         [0.5078],
         [0.2187],
         [0.6330],
         [0.4019],
         [0.4555],
         [0.5203],
         [0.6180],
         [0.3528],
         [0.4015],
         [0.4716],
         [0.4219],
         [0.4205],
         [0.3375],
         [0.4455],
         [0.5928],
         [0.5222],
         [0.5843],
         [0.4074],
         [0.3607],
         [0.5008],
         [0.5213],
         [0.7322],
         [0.2724],
         [0.4134],
         [0.3616],
         [0.2449],
         [0.4350],
         [0.2553],
         [0.2739],
         [0.3120],
         [0.3561],
         [0.1988],
         [0.3913],
         [0.3266],
         [0.2652],
         [0.3357],
         [0.3130],
         [0.5781],
         [0.2038],
         [0.1986],
         [0.5201],
         [0.3552],
         [0.3743],
         [0.3106],
         [0.

In [11]:
preds = np.array([pred for subarr in preds[0].numpy() for pred in subarr])
preds

array([0.6513767 , 0.70462936, 0.5391252 , 0.61739624, 0.45232403, 0.35376212, 0.40217584, 0.30367547, 0.5078317 , 0.21871078, 0.63302517, 0.40186068, 0.45549226, 0.5203176 , 0.61797386, 0.35282162,
       0.4015405 , 0.47158697, 0.42189986, 0.42053625, 0.33745354, 0.44547978, 0.5928091 , 0.5222232 , 0.5842919 , 0.40744928, 0.36066464, 0.50084466, 0.5212598 , 0.7322381 , 0.27241   , 0.41336808,
       0.3616003 , 0.24487436, 0.43502995, 0.25529125, 0.27389446, 0.31199607, 0.3560731 , 0.19883034, 0.3912945 , 0.326615  , 0.2651628 , 0.3357056 , 0.31298262, 0.57812226, 0.20384504, 0.19857666,
       0.52006865, 0.3551841 , 0.37429747, 0.31059903, 0.38022804, 0.25088358, 0.4420119 , 0.3745363 , 0.3572501 , 0.4768943 , 0.34610403, 0.6418643 , 0.2716401 , 0.31344572, 0.37929356, 0.6485191 ,
       0.7104013 , 0.57973796, 0.47921863, 0.30504844, 0.59736043, 0.6907373 , 0.33354315, 0.55185384, 0.60885394, 0.62604606, 0.42779422, 0.2367594 , 0.3197729 , 0.461451  , 0.5753854 , 0.5779405 ,
     

In [12]:
vars(dl)

{'after_item': Pipeline: ,
 'before_batch': Pipeline: ,
 'after_batch': Pipeline: ReadTabBatch,
 '__stored_args__': {'dataset':     state_po  Repub%of_two-party_vote  Dem_cfscore  Repub_cfscore  \
  0          2                 0.640702     0.177173       0.020120   
  1          1                 0.792370     0.177173      -1.614843   
  2          4                 0.568609     0.177173      -0.440143   
  3          3                 0.622993     0.177173      -0.131011   
  4          5                 0.383972    -1.522357       0.076943   
  ..       ...                      ...          ...            ...   
  88        40                 0.552079     0.177173      -0.453882   
  89        42                 0.638852     0.177173       0.076943   
  90        43                 0.549495     0.177173       0.198730   
  91        45                 0.439521     1.320969       0.076943   
  92        49                 0.722461     0.177173      -1.175189   
  
      state enviro 

In [13]:
nn_y = dl.__dict__['dataset']['Repub%of_two-party_vote']
nn_y = np.array(nn_y)
nn_y

array([0.6407024 , 0.79237048, 0.56860915, 0.62299334, 0.38397188, 0.46995547, 0.37506846, 0.53980578, 0.57175417, 0.23206356, 0.70459902, 0.42032449, 0.55130669, 0.62760265, 0.65854281, 0.57274552,
       0.36944741, 0.51460769, 0.4867684 , 0.49928206, 0.26488753, 0.5295356 , 0.82222304, 0.6096339 , 0.73375957, 0.37074179, 0.5074518 , 0.6379825 , 0.71827862, 0.71578547, 0.350267  , 0.4098699 ,
       0.51733264, 0.48798521, 0.54163816, 0.40926667, 0.38680496, 0.50061259, 0.28848902, 0.53081452, 0.77130828, 0.31847168, 0.3748056 , 0.46681431, 0.37518267, 0.59706428, 0.52998317, 0.48171542,
       0.59897514, 0.47376226, 0.44227795, 0.36081558, 0.31543232, 0.55452705, 0.46576329, 0.43457218, 0.38420263, 0.55468602, 0.51293741, 0.6693947 , 0.4184005 , 0.4156624 , 0.44581437, 0.68989095,
       0.60196475, 0.56679518, 0.45228415, 0.38934997, 0.50910642, 0.65320814, 0.41435129, 0.53399623, 0.56018967, 0.60174271, 0.54603539, 0.33311847, 0.49141357, 0.47160271, 0.5507762 , 0.55012161,
     

In [17]:
classif_accur(preds, nn_y)

0.8172043010752689

<font size = 6> Ensemble</font>

In [21]:
rf_preds = best_rf.predict(test_set.train.xs)
ens_preds = (preds + rf_preds) /2

In [22]:
ens_preds

array([0.65060439, 0.69310471, 0.60418249, 0.63361415, 0.41761972, 0.3754504 , 0.38334154, 0.46751687, 0.58552957, 0.28799736, 0.63767265, 0.37940751, 0.54890619, 0.46721904, 0.63390296, 0.48197131,
       0.37924741, 0.56740721, 0.39404338, 0.41453772, 0.35182022, 0.54765592, 0.63102443, 0.57534721, 0.61282778, 0.38727535, 0.39390956, 0.57321252, 0.58717605, 0.71582352, 0.32154091, 0.39201994,
       0.37855872, 0.4422048 , 0.41279013, 0.30429373, 0.31059176, 0.46231464, 0.35316867, 0.39251187, 0.38567995, 0.33634396, 0.31658474, 0.34292545, 0.33277553, 0.6126804 , 0.39916602, 0.4093609 ,
       0.57359008, 0.35524479, 0.36480147, 0.33295225, 0.36831304, 0.44751101, 0.49104076, 0.38547116, 0.35863408, 0.54425135, 0.4723011 , 0.65028827, 0.38098097, 0.33574708, 0.37016935, 0.63768435,
       0.65280382, 0.59803865, 0.49430278, 0.32917232, 0.60474153, 0.65142997, 0.33980803, 0.58198823, 0.6163526 , 0.6305166 , 0.40318444, 0.29351181, 0.33495909, 0.42502022, 0.59961833, 0.59503158,
     

In [24]:
classif_accur(ens_preds,test_set.train.y)

0.8602150537634409

The random forest has the best classification accuracy, even better than the ensemble of it and the neural net.