In [1]:
from fastbook import *
setup_book()

import pandas as pd
import numpy as np
from pandas.api.types import is_string_dtype, is_numeric_dtype, is_categorical_dtype
from fastai.tabular.all import *
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from dtreeviz.trees import *
from IPython.display import Image, display_svg, SVG

<font size = 6> Decision Tree</font>

In [2]:
test_set = pd.read_csv('..\\prepared_data\\test_set_v1.csv')

In [3]:
test_set = test_set.drop(columns=['year','Dem_candidate','Repub_candidate','state']) 

In [4]:
test_set

state_po  Repub%of_two-party_vote  Dem_cfscore  Repub_cfscore  \
0        AL                 0.640702          NaN          0.896   
1        AK                 0.792370          NaN          0.420   
2        AZ                 0.568609          NaN          0.762   
3        AR                 0.622993          NaN          0.852   
4        CA                 0.383972       -1.418            NaN   
..      ...                      ...          ...            ...   
88       SC                 0.552079          NaN          0.758   
89       TN                 0.638852          NaN            NaN   
90       TX                 0.549495          NaN          0.948   
91       VA                 0.439521       -0.408            NaN   
92       WV                 0.722461          NaN          0.548   

    state enviro  Natl_enviro  Inflation  Natl_unempl  
0             14          1.1       1.26         4.87  
1             12          1.1       1.26         4.87  
2              7          1.1       1.26         4.87  
3             14          1.1       1.26         4.87  
4             -9          1.1       1.26         4.87  
..           ...          ...        ...          ...  
88            16         -3.1       1.23         8.05  
89            28         -3.1       1.23         8.05  
90            17         -3.1       1.23         8.05  
91            -7         -3.1       1.23         8.05  
92            33         -3.1       1.23         8.05  

[93 rows x 8 columns]

In [5]:
procs = [Categorify, FillMissing]
dep_var='Repub%of_two-party_vote'

cont = ['Dem_cfscore','Repub_cfscore','state enviro','Natl_enviro','Inflation','Natl_unempl']
cat = ['state_po']

to = TabularPandas(test_set, procs, cat, cont, y_names='Repub%of_two-party_vote', splits=None)

In [6]:
to.classes['state_po'] = ['#na#', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']

In [7]:
save_pickle('..\\prepared_data\\prepared_test_set_v1.pkl',to)

In [8]:
xs = to.train.xs
xs

state_po  Dem_cfscore_na  Repub_cfscore_na  Dem_cfscore  Repub_cfscore  \
0          2               2                 1       -0.660          0.896   
1          1               2                 1       -0.660          0.420   
2          4               2                 1       -0.660          0.762   
3          3               2                 1       -0.660          0.852   
4          5               1                 2       -1.418          0.892   
..       ...             ...               ...          ...            ...   
88        39               2                 1       -0.660          0.758   
89        41               2                 2       -0.660          0.892   
90        42               2                 1       -0.660          0.948   
91        44               1                 2       -0.408          0.892   
92        48               2                 1       -0.660          0.548   

    state enviro  Natl_enviro  Inflation  Natl_unempl  
0             14          1.1       1.26         4.87  
1             12          1.1       1.26         4.87  
2              7          1.1       1.26         4.87  
3             14          1.1       1.26         4.87  
4             -9          1.1       1.26         4.87  
..           ...          ...        ...          ...  
88            16         -3.1       1.23         8.05  
89            28         -3.1       1.23         8.05  
90            17         -3.1       1.23         8.05  
91            -7         -3.1       1.23         8.05  
92            33         -3.1       1.23         8.05  

[93 rows x 9 columns]

In [10]:
dtree = load_pickle('trained_models\\dtree_best.pkl')

In [11]:
dtree.predict(xs)

array([0.61392636, 0.66014414, 0.66014414, 0.61392636, 0.5314384 , 0.54303319, 0.36389214, 0.47045276, 0.54303319, 0.31731838, 0.70709773, 0.36389214, 0.54303319, 0.66014414, 0.61392636, 0.47045276,
       0.31731838, 0.54303319, 0.54303319, 0.66014414, 0.31731838, 0.54303319, 0.66014414, 0.66014414, 0.70709773, 0.44090314, 0.47045276, 0.61392636, 0.61392636, 0.70709773, 0.31731838, 0.44090314,
       0.32723542, 0.51285582, 0.31731838, 0.36389214, 0.36389214, 0.51285582, 0.31731838, 0.47045276, 0.36389214, 0.31731838, 0.5314384 , 0.36389214, 0.51285582, 0.51285582, 0.47045276, 0.51285582,
       0.51285582, 0.51285582, 0.44090314, 0.44090314, 0.31731838, 0.51285582, 0.51285582, 0.51285582, 0.31731838, 0.47045276, 0.47045276, 0.70709773, 0.51285582, 0.44090314, 0.32723542, 0.70709773,
       0.70709773, 0.61392636, 0.54303319, 0.31731838, 0.47045276, 0.70709773, 0.31731838, 0.47045276, 0.70709773, 0.70709773, 0.36389214, 0.31731838, 0.36389214, 0.54303319, 0.61392636, 0.70709773,
     

In [12]:
def r_mse(pred,y): 
    return round(math.sqrt(((pred-y)**2).mean()), 6)
def model_rmse(model, xs, y): 
    return r_mse(model.predict(xs), y)

In [13]:
model_rmse(dtree, xs, to.train.y)

0.092259

Classification Performance on Test Set

In [53]:
def classif_accur(preds, y): 
    pred_margins = preds - 0.500
    pred_repub_wins = np.array([1 if x>0 else 0 for x in pred_margins])
    
    margins = np.array(y - 0.500)
    repub_wins = np.array([1 if x>0 else 0 for x in margins])
    correct = repub_wins==pred_repub_wins

    return sum(correct)/len(correct)

In [54]:
classif_accur(dtree.predict(xs), to.train.y)

0.6989247311827957

<font size = 6 > Random Forest </font>

In [14]:
rf = load_pickle('trained_models\\rf_best.pkl')

In [15]:
rf.predict(xs)

array([0.64983206, 0.68158005, 0.66923978, 0.64983206, 0.38291541, 0.39713869, 0.36450723, 0.63135828, 0.66322745, 0.35728394, 0.64232013, 0.35695433, 0.64232013, 0.41412047, 0.64983206, 0.61112101,
       0.35695433, 0.66322745, 0.3661869 , 0.40853919, 0.3661869 , 0.64983206, 0.66923978, 0.62847124, 0.64136368, 0.36710143, 0.42715449, 0.64558037, 0.65309231, 0.69940893, 0.37067181, 0.37067181,
       0.39551713, 0.63953524, 0.3905503 , 0.3532962 , 0.34728905, 0.6126332 , 0.35026422, 0.5861934 , 0.38006539, 0.34607291, 0.36800669, 0.35014529, 0.35256844, 0.64723855, 0.59448701, 0.62014513,
       0.62711151, 0.35530548, 0.35530548, 0.35530548, 0.35639805, 0.64413845, 0.54006962, 0.39640601, 0.36001807, 0.61160841, 0.59849818, 0.65871223, 0.49032184, 0.35804843, 0.36104514, 0.62684961,
       0.59520634, 0.61633933, 0.50938693, 0.3532962 , 0.61212263, 0.61212263, 0.34607291, 0.61212263, 0.62385126, 0.63498714, 0.37857466, 0.35026422, 0.35014529, 0.38858945, 0.62385126, 0.61212263,
     

In [44]:
model_rmse(rf, xs, to.train.y)

0.091052

<font size = 6> Neural Net</font>

In [17]:
test_set = pd.read_csv('..\\prepared_data\\test_set_v1.csv')

In [18]:
test_set.drop(columns=['year','Dem_candidate','Repub_candidate','state'],inplace=True)
test_set_y = test_set.loc[:,'Repub%of_two-party_vote']
test_set_xs = test_set.drop('Repub%of_two-party_vote', axis=1)

In [20]:
best_net = load_pickle('trained_models\\0.076_error_neural_net.pkl')

In [21]:
# dataloader specifically for inference
dl = best_net.dls.test_dl(test_set)

In [22]:
save_pickle('..\\prepared_data\\dataloader_for_inference_neural_net.pkl',dl)

In [29]:
preds = best_net.get_preds(dl=dl)
preds_series = pd.DataFrame(preds[0].numpy())
preds_series = preds_series.iloc[:,0]

In [30]:
def test_set_r_mse(pred,y): # new rmse function using numpy's swrt. Previous one used math.sqrt, which threw errors
    return round(np.sqrt(((pred-y)**2).mean()), 6)

In [45]:
test_set_r_mse(preds_series,test_set_y)

0.121142

This performance is unsatisfactory, and this is the best neural net, so I will revisit my models and try using Ensembling and Data Augmentation to improve performance.

<font size = 6>Ensembling</font>

In [41]:
rf_preds = rf.predict(xs)
ens_preds = (np.array(preds_series) + rf_preds) /2

In [42]:
ens_preds

array([0.65060439, 0.69310471, 0.60418249, 0.63361415, 0.41761972, 0.3754504 , 0.38334154, 0.46751687, 0.58552957, 0.28799736, 0.63767265, 0.37940751, 0.54890619, 0.46721904, 0.63390296, 0.48197131,
       0.37924741, 0.56740721, 0.39404338, 0.41453772, 0.35182022, 0.54765592, 0.63102443, 0.57534721, 0.61282778, 0.38727535, 0.39390956, 0.57321252, 0.58717605, 0.71582352, 0.32154091, 0.39201994,
       0.37855872, 0.4422048 , 0.41279013, 0.30429373, 0.31059176, 0.46231464, 0.35316867, 0.39251187, 0.38567995, 0.33634396, 0.31658474, 0.34292545, 0.33277553, 0.6126804 , 0.39916602, 0.4093609 ,
       0.57359008, 0.35524479, 0.36480147, 0.33295225, 0.36831304, 0.44751101, 0.49104076, 0.38547116, 0.35863408, 0.54425135, 0.4723011 , 0.65028827, 0.38098097, 0.33574708, 0.37016935, 0.63768435,
       0.65280382, 0.59803865, 0.49430278, 0.32917232, 0.60474153, 0.65142997, 0.33980803, 0.58198823, 0.6163526 , 0.6305166 , 0.40318444, 0.29351181, 0.33495909, 0.42502022, 0.59961833, 0.59503158,
     

In [46]:
r_mse(ens_preds,test_set_y)

0.083401

We get better performance from the ensemble than from either the best random forest or the best neural net.